### PR TITLE
Docs: Update utils/uid documentation.

### LINKED ISSUE #192: The `uid` function has docs describing old behavior
The `uid` method changed to be more UUID like but it's docs does not changed.

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Docs: Update utils/uid documentation. Closes #192.

---

### Additional information

* I cannot look longer on the documentation of this method... I've also updated the test to reflect current uid format.

### CODE REVIEW

**Comment by jodator** [comment]
@Reinmar probably not an issue but there are some UUID implementations that conforms to the RFCs: https://github.com/broofa/node-uuid (have browser version).

**Comment by Reinmar** [comment]
I think that we called it `uid()` instead of `uuid()` for a reason. We need a unique id and its format does not matter. In fact, the fact that it starts with `e` doesn't make any difference. These could be random characters and that's all.

**Comment by Reinmar** [comment]
Actually, this is a question to @czerwonkabartosz. I think that you guys needed changes in this function, right? https://github.com/ckeditor/ckeditor5-utils/issues/192 says that this method's implementation has been changed, but when did it happen and why?

**Comment by czerwonkabartosz** [comment]
Hmmm I'm pretty sure that we do not use that function in our code. I've checked our code and this function is not used by us.

**Comment by Reinmar** [comment]
Thanks. I checked who touched this file and it was changed in https://github.com/ckeditor/ckeditor5-utils/commit/d7a9184fe0e40186b2f8238fd584afec175aeca6. So it wasn't following some requirements, AFAICS. https://github.com/ckeditor/ckeditor5-utils/issues/97 mentions that it was copied from CKE4 :D

Let's leave it like this.

**Comment by czerwonkabartosz** [comment]
I've check changes in https://github.com/ckeditor/ckeditor5-utils/commit/d7a9184fe0e40186b2f8238fd584afec175aeca6 and now I understand... Id items from the collection are saved in our database and should be unique. 

But for us format does not matter ;) it should be unique and this is our requirement.

**Pull request merged**
